// apps/vue/src/App.vue
<script setup lang="ts">
import TopBar from './components/TopBar.vue';
import { resume } from './lib/resume';

const r = resume;
const telHref = `tel:${r.contacts.phone.replace(/[^+\d]/g, '')}`;
const ghShort = r.contacts.github.replace('https://', '');
const year = new Date().getFullYear();

function points(n: number) {
  const last = n % 10;
  const tens = n % 100;
  if (tens >= 11 && tens <= 14) return 'пунктов';
  if (last === 1) return 'пункт';
  if (last >= 2 && last <= 4) return 'пункта';
  return 'пунктов';
}
</script>

<template>
  <TopBar />
  <main class="container">
    <!-- Hero -->
    <header class="hero">
      <div class="hero-avatar">ТГ</div>
      <div class="hero-eyebrow"><span class="pulse" /> Открыт к предложениям</div>
      <h1 class="hero-name">{{ r.name }}</h1>
      <p class="hero-title"><b>{{ r.title }}</b> · опыт {{ r.experienceTotal }}</p>
      <p class="hero-tagline">{{ r.tagline }}</p>

      <div class="facts">
        <div class="fact">
          <div class="fact-label">Город</div>
          <div class="fact-value">{{ r.location }}</div>
        </div>
        <div class="fact">
          <div class="fact-label">Возраст</div>
          <div class="fact-value">{{ r.age }} года</div>
        </div>
        <div class="fact">
          <div class="fact-label">Формат работы</div>
          <div class="fact-value">{{ r.workFormats.join(', ') }}</div>
        </div>
        <div class="fact">
          <div class="fact-label">Занятость</div>
          <div class="fact-value">{{ r.employmentTypes.join(', ') }}</div>
        </div>
      </div>

      <div class="contact-row">
        <a class="contact" :href="telHref">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
            <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.9.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z" />
          </svg>
          {{ r.contacts.phone }}
        </a>
        <a class="contact" :href="`mailto:${r.contacts.email}`">
          <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">
            <rect x="2" y="4" width="20" height="16" rx="2" />
            <path d="m22 7-10 6L2 7" />
          </svg>
          {{ r.contacts.email }}
        </a>
        <a class="contact" :href="r.contacts.github" target="_blank" rel="noreferrer">
          <svg viewBox="0 0 24 24" fill="currentColor">
            <path d="M12 .5C5.7.5.5 5.7.5 12c0 5.1 3.3 9.4 7.9 10.9.6.1.8-.3.8-.6v-2c-3.2.7-3.9-1.5-3.9-1.5-.5-1.3-1.3-1.7-1.3-1.7-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.7-1.6-2.6-.3-5.3-1.3-5.3-5.7 0-1.3.5-2.3 1.2-3.1-.1-.3-.5-1.5.1-3.1 0 0 1-.3 3.3 1.2a11.5 11.5 0 0 1 6 0C17 4.6 18 4.9 18 4.9c.6 1.6.2 2.8.1 3.1.8.8 1.2 1.8 1.2 3.1 0 4.4-2.7 5.4-5.3 5.7.4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.6 4.6-1.5 7.9-5.8 7.9-10.9C23.5 5.7 18.3.5 12 .5z" />
          </svg>
          {{ ghShort }}
        </a>
      </div>
    </header>

    <!-- О себе -->
    <section class="section">
      <h2 class="section-title">О себе</h2>
      <p class="about-text">{{ r.about }}</p>
    </section>

    <!-- Опыт -->
    <section class="section">
      <h2 class="section-title">Опыт работы</h2>
      <div class="job" v-for="job in r.experience" :key="job.company">
        <div class="job-header">
          <div>
            <div class="job-company">
              <a v-if="job.companyUrl" :href="job.companyUrl" target="_blank" rel="noreferrer">{{ job.company }}</a>
              <template v-else>{{ job.company }}</template>
              <span v-if="job.current" class="badge-current">
                <span class="pulse" :style="{ width: '6px', height: '6px' }" /> сейчас
              </span>
            </div>
            <div class="job-role">{{ job.role }}</div>
            <div v-if="job.industry" class="job-industry">{{ job.industry }}</div>
          </div>
          <div class="job-period">
            {{ job.period }}<br />
            <span class="job-duration">{{ job.duration }}</span>
          </div>
        </div>

        <article class="project" v-for="p in job.projects" :key="p.name">
          <div class="project-header">
            <div class="project-name">
              <a v-if="p.url" :href="p.url" target="_blank" rel="noreferrer">{{ p.name }}</a>
              <template v-else>{{ p.name }}</template>
            </div>
            <span class="project-role">{{ p.role }}</span>
          </div>
          <p v-if="p.summary" class="project-summary">{{ p.summary }}</p>

          <div v-if="p.stack.length" class="chips">
            <span v-for="s in p.stack" :key="s" class="chip mono">{{ s }}</span>
          </div>

          <div v-if="p.brands && p.brands.length" class="brands">
            <span v-for="b in p.brands" :key="b" class="brand-chip">{{ b }}</span>
          </div>

          <details v-if="p.highlights.length" class="details">
            <summary class="details-summary">
              Что внутри — {{ p.highlights.length }} {{ points(p.highlights.length) }}
            </summary>
            <ul class="highlights">
              <li v-for="h in p.highlights" :key="h.title" class="highlight">
                <span class="highlight-title">{{ h.title }}.</span> {{ h.text }}
              </li>
            </ul>
          </details>

          <div v-if="p.metrics && p.metrics.length" class="metrics">
            <span v-for="m in p.metrics" :key="m" class="metric">{{ m }}</span>
          </div>
        </article>
      </div>
    </section>

    <!-- Навыки -->
    <section class="section">
      <h2 class="section-title">Навыки</h2>
      <div class="skills-grid">
        <div class="skill-group" v-for="g in r.skills" :key="g.group">
          <div class="skill-group-title">{{ g.group }}</div>
          <div class="chips">
            <span v-for="s in g.items" :key="s" class="chip">{{ s }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- Образование и языки -->
    <section class="section">
      <h2 class="section-title">Образование и языки</h2>
      <div class="cards">
        <div class="card" v-for="e in r.education" :key="e.institution">
          <div class="card-title">{{ e.institution }}</div>
          <div class="card-sub">{{ e.degree }} · {{ e.year }}</div>
          <div class="card-meta">{{ e.faculty }} · {{ e.location }}</div>
        </div>
        <div class="card">
          <div class="card-title">Языки</div>
          <div class="lang-row" v-for="l in r.languages" :key="l.name">
            <span>{{ l.name }}</span>
            <span class="lang-level">{{ l.level }}</span>
          </div>
        </div>
      </div>
    </section>

    <!-- Пет-проекты -->
    <section class="section">
      <h2 class="section-title">Пет-проекты</h2>
      <div class="cards">
        <div class="card" v-for="p in r.petProjects" :key="p.name">
          <div class="card-title">{{ p.name }}</div>
          <p class="pet-desc">{{ p.description }}</p>
          <a v-if="p.url" class="contact" :style="{ marginTop: '14px' }" :href="p.url" target="_blank" rel="noreferrer">
            <svg viewBox="0 0 24 24" fill="currentColor">
              <path d="M12 .5C5.7.5.5 5.7.5 12c0 5.1 3.3 9.4 7.9 10.9.6.1.8-.3.8-.6v-2c-3.2.7-3.9-1.5-3.9-1.5-.5-1.3-1.3-1.7-1.3-1.7-1.1-.7.1-.7.1-.7 1.2.1 1.8 1.2 1.8 1.2 1 1.8 2.8 1.3 3.5 1 .1-.8.4-1.3.7-1.6-2.6-.3-5.3-1.3-5.3-5.7 0-1.3.5-2.3 1.2-3.1-.1-.3-.5-1.5.1-3.1 0 0 1-.3 3.3 1.2a11.5 11.5 0 0 1 6 0C17 4.6 18 4.9 18 4.9c.6 1.6.2 2.8.1 3.1.8.8 1.2 1.8 1.2 3.1 0 4.4-2.7 5.4-5.3 5.7.4.4.8 1.1.8 2.2v3.3c0 .3.2.7.8.6 4.6-1.5 7.9-5.8 7.9-10.9C23.5 5.7 18.3.5 12 .5z" />
            </svg>
            Открыть на GitHub
          </a>
        </div>
      </div>
    </section>
  </main>

  <footer class="footer">
    <div class="container">
      <div>© {{ year }} {{ r.shortName }} · {{ r.title }}</div>
      <div class="footer-note">
        Vue 3 + Vite · <a href="../">та же страница на Next.js</a>
      </div>
    </div>
  </footer>
</template>

// apps/next/app/page.tsx
import { resume as r } from '@/lib/resume';
import { TopBar } from '@/components/TopBar';
import { PhoneIcon, MailIcon, GitHubIcon } from '@/components/icons';

function Chips({ items, mono }: { items: string[]; mono?: boolean }) {
  if (!items?.length) return null;
  return (
    <div className="chips">
      {items.map((s) => (
        <span key={s} className={mono ? 'chip mono' : 'chip'}>
          {s}
        </span>
      ))}
    </div>
  );
}

function points(n: number) {
  const last = n % 10;
  const tens = n % 100;
  if (tens >= 11 && tens <= 14) return 'пунктов';
  if (last === 1) return 'пункт';
  if (last >= 2 && last <= 4) return 'пункта';
  return 'пунктов';
}

export default function Home() {
  const telHref = `tel:${r.contacts.phone.replace(/[^+\d]/g, '')}`;
  const ghShort = r.contacts.github.replace('https://', '');

  return (
    <>
      <TopBar />
      <main className="container">
        {/* ---------- Hero ---------- */}
        <header className="hero">
          <div className="hero-avatar">ТГ</div>
          <div className="hero-eyebrow">
            <span className="pulse" /> Открыт к предложениям
          </div>
          <h1 className="hero-name">{r.name}</h1>
          <p className="hero-title">
            <b>{r.title}</b> · опыт {r.experienceTotal}
          </p>
          <p className="hero-tagline">{r.tagline}</p>

          <div className="facts">
            <div className="fact">
              <div className="fact-label">Город</div>
              <div className="fact-value">{r.location}</div>
            </div>
            <div className="fact">
              <div className="fact-label">Возраст</div>
              <div className="fact-value">{r.age} года</div>
            </div>
            <div className="fact">
              <div className="fact-label">Формат работы</div>
              <div className="fact-value">{r.workFormats.join(', ')}</div>
            </div>
            <div className="fact">
              <div className="fact-label">Занятость</div>
              <div className="fact-value">{r.employmentTypes.join(', ')}</div>
            </div>
          </div>

          <div className="contact-row">
            <a className="contact" href={telHref}>
              <PhoneIcon /> {r.contacts.phone}
            </a>
            <a className="contact" href={`mailto:${r.contacts.email}`}>
              <MailIcon /> {r.contacts.email}
            </a>
            <a className="contact" href={r.contacts.github} target="_blank" rel="noreferrer">
              <GitHubIcon /> {ghShort}
            </a>
          </div>
        </header>

        {/* ---------- О себе ---------- */}
        <section className="section">
          <h2 className="section-title">О себе</h2>
          <p className="about-text">{r.about}</p>
        </section>

        {/* ---------- Опыт ---------- */}
        <section className="section">
          <h2 className="section-title">Опыт работы</h2>
          {r.experience.map((job) => (
            <div className="job" key={job.company}>
              <div className="job-header">
                <div>
                  <div className="job-company">
                    {job.companyUrl ? (
                      <a href={job.companyUrl} target="_blank" rel="noreferrer">
                        {job.company}
                      </a>
                    ) : (
                      job.company
                    )}
                    {job.current && (
                      <span className="badge-current">
                        <span className="pulse" style={{ width: 6, height: 6 }} /> сейчас
                      </span>
                    )}
                  </div>
                  <div className="job-role">{job.role}</div>
                  {job.industry && <div className="job-industry">{job.industry}</div>}
                </div>
                <div className="job-period">
                  {job.period}
                  <br />
                  <span className="job-duration">{job.duration}</span>
                </div>
              </div>

              {job.projects.map((p) => (
                <article className="project" key={p.name}>
                  <div className="project-header">
                    <div className="project-name">
                      {p.url ? (
                        <a href={p.url} target="_blank" rel="noreferrer">
                          {p.name}
                        </a>
                      ) : (
                        p.name
                      )}
                    </div>
                    <span className="project-role">{p.role}</span>
                  </div>
                  {p.summary && <p className="project-summary">{p.summary}</p>}
                  <Chips items={p.stack} mono />
                  {p.brands && p.brands.length > 0 && (
                    <div className="brands">
                      {p.brands.map((b) => (
                        <span key={b} className="brand-chip">
                          {b}
                        </span>
                      ))}
                    </div>
                  )}
                  {p.highlights.length > 0 && (
                    <details className="details">
                      <summary className="details-summary">
                        Что внутри — {p.highlights.length} {points(p.highlights.length)}
                      </summary>
                      <ul className="highlights">
                        {p.highlights.map((h) => (
                          <li className="highlight" key={h.title}>
                            <span className="highlight-title">{h.title}.</span> {h.text}
                          </li>
                        ))}
                      </ul>
                    </details>
                  )}
                  {p.metrics && p.metrics.length > 0 && (
                    <div className="metrics">
                      {p.metrics.map((m) => (
                        <span key={m} className="metric">
                          {m}
                        </span>
                      ))}
                    </div>
                  )}
                </article>
              ))}
            </div>
          ))}
        </section>

        {/* ---------- Навыки ---------- */}
        <section className="section">
          <h2 className="section-title">Навыки</h2>
          <div className="skills-grid">
            {r.skills.map((g) => (
              <div className="skill-group" key={g.group}>
                <div className="skill-group-title">{g.group}</div>
                <Chips items={g.items} />
              </div>
            ))}
          </div>
        </section>

        {/* ---------- Образование и языки ---------- */}
        <section className="section">
          <h2 className="section-title">Образование и языки</h2>
          <div className="cards">
            {r.education.map((e) => (
              <div className="card" key={e.institution}>
                <div className="card-title">{e.institution}</div>
                <div className="card-sub">
                  {e.degree} · {e.year}
                </div>
                <div className="card-meta">
                  {e.faculty} · {e.location}
                </div>
              </div>
            ))}
            <div className="card">
              <div className="card-title">Языки</div>
              {r.languages.map((l) => (
                <div className="lang-row" key={l.name}>
                  <span>{l.name}</span>
                  <span className="lang-level">{l.level}</span>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* ---------- Пет-проекты ---------- */}
        <section className="section">
          <h2 className="section-title">Пет-проекты</h2>
          <div className="cards">
            {r.petProjects.map((p) => (
              <div className="card" key={p.name}>
                <div className="card-title">{p.name}</div>
                <p className="pet-desc">{p.description}</p>
                {p.url && (
                  <a className="contact" style={{ marginTop: 14 }} href={p.url} target="_blank" rel="noreferrer">
                    <GitHubIcon /> Открыть на GitHub
                  </a>
                )}
              </div>
            ))}
          </div>
        </section>
      </main>

      <footer className="footer">
        <div className="container">
          <div>
            © {new Date().getFullYear()} {r.shortName} · {r.title}
          </div>
          <div className="footer-note">
            Next.js + React · <a href="vue/">та же страница на Vue</a>
          </div>
        </div>
      </footer>
    </>
  );
}
